### ISSUE TITLE
Wrong mouse cursor

### ISSUE THREAD

**Issue by mihailescu2m** [Igalia/chromium#469] opened 2018-07-25 09:48 UTC
Sometimes the mouse pointer gets stuck with the wrong cursor.
For example, after hovering a link, the mouse pointer is stuck to the hand icon all over the chrome window (including titlebar). Outside chrome window is ok.

**Comment by mntmn** [comment] 2018-09-05 20:35
Confirmed, I have the same problem.

**Comment by msisov** [comment] 2018-09-05 21:01
The team is aware of the problem, but is busy with more important stuff. Also, most of the patches go directly to upstream and may not be explicitly merged here.

**Comment by mntmn** [comment] 2018-09-05 21:18
Alright, thanks for the quick answer

**Comment by mntmn** [comment] 2018-09-05 21:21
As a workaround, would it be possible to disable cursor changing in general? Maybe you can point me to the right method to patch locally?

**Comment by msisov** [comment] 2018-10-16 06:56
is it still applicable?

**Comment by nickdiego** [comment] 2019-01-02 16:10
Hi @msisov, Just checked with the latest version and couldn't reproduce this issue.

**Comment by hedgepigdaniel** [comment] 2019-02-04 13:10
I still find that the cursor is often wrong, as of a011df391c95d05da092c2468fe231c8911e5e82. I'm not sure what the pattern is - it seems to get stuck, e.g. the :point_up_2: gets stuck and remains even when going over the tabs, or vice versa the default pointer remains when mousing over a link.

Theres a few of
```
ERROR:window_tree_host_platform.cc(197)] Not implemented reached in virtual void aura::WindowTreeHostPlatform::OnCursorVisibilityChangedNative(bool)
```
and
```
ERROR:wayland_screen.cc(132)] Not implemented reached in virtual gfx::Point ui::WaylandScreen::GetCursorScreenPoint() const
```

**Comment by msisov** [comment] 2019-02-04 13:20
The issue is moved to upstream.

https://bugs.chromium.org/p/chromium/issues/detail?id=928260

**Closed as completed by msisov** 2019-02-04 13:20 UTC
Labels: external, desktop_aura
