### ISSUE TITLE
Progress of the project? Any idea on when nightly binaries will be available?

### ISSUE THREAD

**Issue by ammen99** [Igalia/chromium#232] opened 2017-09-12 16:04 UTC
In one of the blogs you said that you plan on releasing nightly binaries, however there has been some time since then. Do you have an idea if(and when) this will happen? Any milestones that should be reached till then? Anyway, this is a great effort, keep up the good work!

**Comment by tonikitoo** [comment] 2017-09-12 20:11
A bit of taste of the progresses can be seen here: https://www.youtube.com/watch?v=bPK966yHQM4 . This is the very latest Chromium/Wayland on Fedora 26 (GNOME/Wayand).

Doing packaging for distribution at this point is a bit more troublesome for us, but not impossible. I explain:

- as per our "rebase strategy" (see README in https://github.com/Igalia/chromium/), we rebase against Chromium tip of trunk (ToT) every week. Apart from adapting to upstreaming contributions and fix any possible regression, we still need to fix existing issues (see https://github.com/Igalia/chromium/issues/) and continue with regular development.

- Also, because we are based on Chromium's development channel  (this is ToT), it is natural that we inherit unrelated instability, that every major project has on their master branch. In order to package Chromium/Wayland for distribution, we would need to a) switch to a stable channel (either 'beta' or 'stable').

I still think it is important since it would allow early testing, and more bug reports, but just explaining why it is done yet :)

**Comment by msisov** [comment] 2017-09-28 08:52
Hi, we rebased our patches against beta 62.0.3202.29 release - https://github.com/Igalia/chromium/tree/ozone-wayland-beta-62.0.3202.29-release .

In theory, it should be a bit more stable. You can try to use it and report us how it goes.

**Comment by ammen99** [comment] 2017-09-29 07:41
@msisov  I used the beta a bit, didn't get any crashes or similar, except the issues we already know of!

**Comment by tonikitoo** [comment] 2017-09-29 13:37
Closing in favor of specific bugs (that we, yourself included, are filing).

**Closed as completed by tonikitoo** 2017-09-29 13:37 UTC
Labels: external
