### ISSUE TITLE
Sign in to chromium doesn't work

### ISSUE THREAD

**Issue by ammen99** [Igalia/chromium#258] opened 2017-09-29 05:51 UTC
Try the following: click on the sign-in to chromium(top right, next to minimize/close buttons). A "pop-up" shows, there is the semicircle which indicates loading, but then the pop-up remains blank and only a "X" for closing it is visible, see the picture below:
![screenshot-2017-09-29-08 46 44](https://user-images.githubusercontent.com/6287487/31002411-4d237804-a4f3-11e7-9511-cbb1e2537d05.png)

EDIT: happens on both chromium 62 and 63 branches

**Comment by msisov** [comment] 2017-10-03 17:33
Upstream bug. Should be fixed soon

**Comment by msisov** [comment] 2017-10-11 10:05
Ok, now OOPIF embedding works with mus and the issue is fixed.

For the record:
bug https://bugs.chromium.org/p/chromium/issues/detail?id=758387
cl https://chromium-review.googlesource.com/c/chromium/src/+/673066

**Closed as completed by msisov** 2017-10-11 10:05 UTC
Labels: upstream_bug, fixed_upstream, external
