### ISSUE TITLE
gn args --check <out> fails

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#510] opened 2018-12-26 20:58 UTC
<out>$ gn args --check out/ozone/linux_os
Waiting for editor on "/out/ozone/linux_os/args.gn"...
Generating files...
ERROR at //ui/base/ime/linux/fake_input_method_context_factory.h:10:11: Include not allowed.
#include "ui/base/ime/ui_base_ime_export.h"
          ^-------------------------------
It is not in any dependency of
  //ui/base/ime/linux:linux
The include file is in the target(s):
  //ui/base/ime:ime
which should somehow be reachable.
___________________
ERROR at //ui/ozone/platform/x11/x11_window_ozone.h:11:11: Include not allowed.
#include "ui/platform_window/platform_window_handler/wm_move_resize_handler.h"
          ^------------------------------------------------------------------
It is not in any dependency of
  //ui/ozone/platform/x11:x11
The include file is in the target(s):
  //ui/platform_window/platform_window_handler:platform_window_handler
which should somehow be reachable.
___________________
ERROR at //ui/platform_window/x11/x11_window_base.h:21:11: Include not allowed.
#include "ui/platform_window/platform_window_handler/wm_drag_handler.h"
          ^-----------------------------------------------------------
It is not in any dependency of
  //ui/platform_window/x11:x11
The include file is in the target(s):
  //ui/platform_window/platform_window_handler:platform_window_handler
which should somehow be reachable.
___________________
ERROR at //ui/platform_window/x11/window_move_loop_client.h:16:11: Include not allowed.
#include "ui/views/views_export.h"
          ^----------------------
It is not in any dependency of
  //ui/platform_window/x11:x11
The include file is in the target(s):
  //ui/views:views
which should somehow be reachable.
___________________
ERROR at //ui/platform_window/x11/window_move_loop_client.h:17:11: Include not allowed.
#include "ui/wm/public/window_move_client.h"
          ^--------------------------------
It is not in any dependency of
  //ui/platform_window/x11:x11
The include file is in the target(s):
  //ui/wm/public:public
which should somehow be reachable.

**Comment by nickdiego** [comment] 2019-01-02 16:06
Hi @tonikitoo, couldn't reproduce this issue on my env.
Could you provide your `gn args`? Or maybe you missed a `gclient sync`?
Thanks for reporting this.

**Comment by nickdiego** [comment] 2019-01-02 18:49
Oops, just got it, was trying with usptream/master branch :)

**Comment by msisov** [comment] 2019-01-15 07:44
Fixed during today's rebasing. Closing.

**Closed as completed by msisov** 2019-01-15 07:44 UTC
